### ISSUE TITLE
Bugs while lauching Minecraft

### ISSUE THREAD

**Issue by mstaczek** [Filmos/FilmPack#27]
Bugs such as:
- [Server-Worker-5/WARN]: Exception loading blockstate definition
- [Server-Worker-5/WARN]: Unable to load model: 
are mainly caused by 'mysticalagriculture' but also by 'jaopca:storage_blocks',  'jaopca:mekanism_clumps',  'jaopca:mekanism_dirty_dusts', 'jaopca:mekanism_shards' and others.

**Comment by Filmos** [comment]
Nie wydaje powodować problemów poza śmietnikiem w logach, zamykam
