### ISSUE TITLE
Veinminer works with obsidian

### ISSUE THREAD

**Issue by mstaczek** [Filmos/FilmPack#33]
and it should not

**Comment by Filmos** [comment]
Ogólnie vein miner nie powinien działać na bloki które służą do znacznego wzmocnienia bazy (ogólnie bloki obsydianowe, ale pewnie parę innych można by dodać).
Dla takich bloków przydałby się także jakiś tooltip że jest "veinminer proof".

**Comment by mstaczek** [comment]
Solution - paste `"minecraft:obsidian"` to block blacklist in file oreexcavation-common.toml
