### ISSUE TITLE
Żelazo jako ziemia w doniczce

### ISSUE THREAD

**Issue by Filmos** [Filmos/FilmPack#42]
![image](https://user-images.githubusercontent.com/21157064/87284952-3f870180-c4f7-11ea-8368-2a8da4851d25.png)

Nie da się tego użyć wewnątrz gry, ale pokazuje się w JEI

**Comment by mstaczek** [comment]
Update BotanyPots to version 2.0.27

**Comment by Filmos** [comment]
Aktualizacja naprawiła problem
